[package]
name = "reflex"
version = "0.2.0"
description = "A minimal flex-like lexer"
license = "MIT"
repository = "https://github.com/jqkul/reflex"
authors = ["jqkul"]

[dependencies]
regex = "1.1.0"
